version: '3'
services:
    # 參考網址1: https://onexlab-io.medium.com/google-cloud-spanner-emulator-setup-2798df2dc9eb
    # 參考網址2: https://github.com/tarosaiba/docker-compose-spanner/blob/master/docker-compose.yaml
    # Spanner
    spanner:
     image: gcr.io/cloud-spanner-emulator/emulator:1.2.0
     ports:
         - "9010:9010"
         - "9020:9020"

    # Init (Create Instance)
    gcloud-spanner-init:
      image: gcr.io/google.com/cloudsdktool/cloud-sdk:332.0.0-slim
      # gcloud config configurations create emulator ==> 初始化過後就不用再做一次
      command: >
       bash -c 'gcloud config set auth/disable_credentials true &&
               gcloud config set project $${PROJECT_ID} &&
               gcloud config set api_endpoint_overrides/spanner $${SPANNER_EMULATOR_URL} &&
               gcloud config set auth/disable_credentials true &&
               gcloud spanner instances create $${INSTANCE_NAME} --config=emulator-config --description=Emulator --nodes=1
               gcloud spanner databases create $${DATABASE_NAME} --instance=$${INSTANCE_NAME}'
      environment:
        PROJECT_ID: "test-project"
        SPANNER_EMULATOR_URL: "http://spanner:9020/"
        INSTANCE_NAME: "test-instance"
        DATABASE_NAME: "test-database"

    # CLI
    spanner-cli:
      image: sjdaws/spanner-cli:v1.0.0
      environment:
        SPANNER_EMULATOR_HOST: "spanner:9010"
      command: ['sh', '-c', 'echo this container keep running && tail -f /dev/null']

